---
# tasks file for vagrant/Debian
- name: Fetch Vagrant public key
  tags: [vagrant, wget, public_key, signing_key]
  ansible.builtin.get_url:
    url: "{{ vagrant_public_key_url }}"
    dest: "{{ vagrant_public_key_local }}"
    mode: "0600"

- name: Dearmor Vagrant signing key
  tags: [vagrant, signing_key]
  become: true
  ansible.builtin.command:
    creates: "{{ vagrant_signing_key }}"
    argv:
      - gpg
      - --yes
      - --output
      - "{{ vagrant_signing_key }}"
      - --dearmor
      - "{{ vagrant_public_key_local }}"

- name: Write Vagrant apt sources
  tags: [vagrant, apt_repo]
  become: true
  ansible.builtin.template:
    src: hashicorp.list.j2
    dest: "{{ vagrant_sources_list }}"
    mode: "0644"
    owner: root
    group: root

- name: Install packages
  tags: [vagrant, apt_install]
  become: true
  ansible.builtin.apt:
    name: "{{ vagrant_packages }}"
    state: latest  # noqa package-latest
    update_cache: true
    # only_upgrade: true  # Currently doesn't work, hence noqa
