---
- name: Verify vagrant role (Default values)
  hosts: linux
  gather_facts: true
  pre_tasks:
    - name: Load per OS variables (avoid post-INJECT_FACTS_AS_VARS migration warning)
      tags: [vagrant, variables]
      ansible.builtin.include_vars:
        file: "{{ vars_file }}"
      loop:
        - "../../vars/main.yml"
        - "../../vars/{{ ansible_facts['os_family'] }}.yml"
      loop_control:
        loop_var: vars_file
  tasks:
    - name: Check that the vagrant_command is on the path
      ansible.builtin.command: "which {{ vagrant_command }}"  # noqa no-changed-when
      register: vagrant_which_register
      changed_when: false
      failed_when: vagrant_which_register.rc == 1
