---
- name: Verify install_virtualization_tools.yml playbook
  hosts: linux
  gather_facts: false
  vars:
    verify_tools:
      - vagrant
      - virtualbox
  pre_tasks:
    - name: Load role command name vars for virtualization tools
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/roles/{{ item }}/vars/main.yml"
      loop: "{{ verify_tools }}"
  tasks:
    - name: Check installation of virtualization tools
      ansible.builtin.command: "which {{ lookup('vars', item + '_command') }}"  # noqa no-changed-when
      check_mode: false
      changed_when: false
      register: which_result
      failed_when: which_result.rc == 1
      loop: "{{ verify_tools }}"
