# In the event we need to do additional prep, this playbook allows us to execute
# the driver specific prepare playbook first, which sets up Python on the host.
# To use, add this to the top of your prepare.yml:
# - import_playbook: "../resources/playbooks/prepare_default.yml"
- name: Execute the driver specific prepare.yml
  import_playbook: "{{ MOLECULE_PLUGINS_PATH }}/molecule_plugins/{{ MOLECULE_DRIVER_NAME }}/playbooks/prepare.yml"
  vars:
    MOLECULE_PLUGINS_PATH: "{{ lookup('ansible.builtin.pipe', 'pip show molecule-plugins') | regex_search('(Location: )(.*)', '\\2') | first }}"
    MOLECULE_DRIVER_NAME: "{{ lookup('ansible.builtin.env', 'MOLECULE_DRIVER_NAME') }}"
