---
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg  # Relative to molecule test dir
  inventory:
    group_vars:
      linux:
        ansible_python_interpreter: /usr/bin/python3
