---
scenario:
  test_sequence:
    # - dependency
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
  destroy_sequence:
    - destroy
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg  # Relative to molecule playbook?
  inventory:
    group_vars:
      linux:
        ansible_python_interpreter: /usr/bin/python3
