---
scenario:
  test_sequence:
    # - dependency
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
  destroy_sequence:
    - destroy
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ${MOLECULE_PROJECT_DIRECTORY}/ansible.cfg
