name: CI for ansible-collection-infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ANSIBLE_FORCE_COLOR: '1'
  ANSIBLE_VERBOSITY: 1
  PY_COLORS: '1'
  VAGRANT_VERSION: 2.4.3-1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    # The type of runner that the job will run on
    # This image already has Python and various container utils
    # https://github.com/actions/runner-images/blob/ubuntu22/20240603.1/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  #v7.0.0

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe  #v24.1.0

      - name: Install project dependencies
        run: |
          cd "$GITHUB_WORKSPACE" || exit 1
          pip install -r python-requirements.txt
          ansible-galaxy install -r ansible-requirements.yml

      - name: Lint ansible files
        run: |
          cd "$GITHUB_WORKSPACE" || exit 1
          ansible-lint
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  #v7.0.0

      - name: Install project dependencies
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          # shellcheck disable=SC2086
          sudo apt update && sudo apt install virtualbox vagrant=$VAGRANT_VERSION parallel
          cd "$GITHUB_WORKSPACE" || exit 1
          pip install -r python-requirements.txt
          ansible-galaxy install -r ansible-requirements.yml

      - name: Add the vagrant boxes to prevent race conditions during parallel molecule tests
        run: |
          echo "Sockets: $( parallel --number-of-sockets )"
          echo "Cores: $( parallel --number-of-cores )"
          echo "Threads: $( parallel --number-of-threads )"
          parallel vagrant box add --provider virtualbox --no-tty {} ::: bento/ubuntu-22.04

      - name: Hack for GH-49 (missing fqcn in molecule_plugins/vagrant)
        run: |
          export MP_PATH=$( pip show molecule-plugins | grep Location | cut -d' ' -f2 )
          sed -i.bu 's/\([^\.]\)\(vagrant:\)/\1community.vagrant.\2/' "${MP_PATH}"/molecule_plugins/vagrant/playbooks/*.yml
          grep -C2 "community.vagrant" "${MP_PATH}"/molecule_plugins/vagrant/playbooks/*.yml

      - name: Run molecule playbook tests in parallel
        run: |
          # parallel exit code = number of tests not executed... expecting 1
          # shellcheck disable=SC1083
          parallel --filter='"{/}" ne "resources"' molecule test -s {/} ::: molecule/* || (PARALLEL_RC=$? && [ "$PARALLEL_RC" -eq 1 ] || exit "$PARALLEL_RC")
